# Generated by Django 4.2.9 on 2024-03-14 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('place', models.CharField(max_length=120)),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_hotspot', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('place', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('cropped_video', models.FileField(blank=True, null=True, upload_to='cropped_video/')),
                ('crimetype', models.CharField(default='None', max_length=120)),
                ('duration', models.IntegerField(default=1, null=True)),
                ('start_duration', models.IntegerField(default=1, null=True)),
                ('end_duration', models.IntegerField(default=1, null=True)),
                ('classified', models.CharField(default=False, max_length=120)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.camera')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, max_length=120)),
                ('name', models.CharField(default='None', max_length=120, unique=True)),
                ('designation', models.CharField(default='None', max_length=120)),
                ('department', models.CharField(default='None', max_length=120)),
                ('mail', models.CharField(default='None', max_length=120)),
                ('mobile', models.CharField(default='None', max_length=120)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('face_df', jsonfield.fields.JSONField(default='None', null=True)),
                ('label_df', jsonfield.fields.JSONField(default='None', null=True)),
                ('object_df', jsonfield.fields.JSONField(default='None', null=True)),
                ('safe_df', jsonfield.fields.JSONField(default='None', null=True)),
                ('cloth_color_df', jsonfield.fields.JSONField(default='None', null=True)),
                ('query', models.IntegerField(default=1, null=True, unique=True)),
                ('query_img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
    ]
