# Generated by Django 4.2.9 on 2024-03-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_camera_hotspot_video_user_suspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='query_img',
            field=models.ImageField(blank=True, null=True, upload_to='istatic/assets/images/mg/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cropped_video',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/images/cropped_video/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/images/video/'),
        ),
    ]
